name: ledgerly
description: "Ledgerly - offline-first freelance invoice & client manager with encrypted storage and PDF export."
publish_to: 'none'

version: 1.6.1+10

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  fl_chart: ^1.2.0
  uuid: ^4.5.3
  intl: ^0.20.3
  pdf: ^3.12.0
  printing: ^5.14.3
  path_provider: ^2.1.6
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  image_picker: ^1.1.2
  image: ^4.3.0
  share_plus: ^10.1.4
  file_picker: ^10.1.9
  core_crypto:
    git:
      url: https://github.com/MalicKAbdullah/secure-suite-core.git
      path: core_crypto
      ref: 2e656ff9d26a8ba458438842096a081a0339b308
  core_storage:
    git:
      url: https://github.com/MalicKAbdullah/secure-suite-core.git
      path: core_storage
      ref: 2e656ff9d26a8ba458438842096a081a0339b308
  core_theme:
    git:
      url: https://github.com/MalicKAbdullah/secure-suite-core.git
      path: core_theme
      ref: 2e656ff9d26a8ba458438842096a081a0339b308
  core_ui:
    git:
      url: https://github.com/MalicKAbdullah/secure-suite-core.git
      path: core_ui
      ref: 2e656ff9d26a8ba458438842096a081a0339b308
  core_backup:
    git:
      url: https://github.com/MalicKAbdullah/secure-suite-core.git
      path: core_backup
      ref: 2e656ff9d26a8ba458438842096a081a0339b308
  core_lock:
    git:
      url: https://github.com/MalicKAbdullah/secure-suite-core.git
      path: core_lock
      ref: 2e656ff9d26a8ba458438842096a081a0339b308
  core_notify:
    git:
      url: https://github.com/MalicKAbdullah/secure-suite-core.git
      path: core_notify
      ref: 2e656ff9d26a8ba458438842096a081a0339b308
  core_update:
    git:
      url: https://github.com/MalicKAbdullah/secure-suite-core.git
      path: core_update
      ref: 2e656ff9d26a8ba458438842096a081a0339b308
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  adaptive_icon_background: "#4F46E5"
  adaptive_icon_foreground: assets/icon/icon_foreground.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
